name: CI/CD Fraud Detection API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Add your pytest commands here"
          # Example: pytest tests/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t fraud-detection-api .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag fraud-detection-api ${{ secrets.DOCKER_USERNAME }}/fraud-detection-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fraud-detection-api:latest
